a2-s3673712-s3719368/a2-s3673712-s3719368/Areas/Default/Controllers/ATMController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using a2_s3673712_s3719368.Data;
using a2_s3673712_s3719368.Models;
using a2_s3673712_s3719368.Attributes;
using Microsoft.AspNetCore.Http;
using a2_s3673712_s3719368.LogicManger;

namespace a2_s3673712_s3719368.Controllers
{
    [Area("default")]
    [AuthorizeCustomer]
    public class ATMController : Controller
    {
        private readonly NationBankContext _context;
        private int CustomerID => HttpContext.Session.GetInt32(nameof(Customer.CustomerID)).Value; //get CustomerID from session
        private List<Account> accountList;
        private TransferManger manager;
        private TransferManger Manager { get
            {
                if (manager == null)
                {
                    manager = new TransferManger(_context, this, CustomerID);
                }
                return manager;
            }  }

        public ATMController(NationBankContext context)
        {
            _context = context;
        }

    

        // GET: ATM
        public async Task<IActionResult> Transfer()
        {
            var customer = await _context.Customers.FindAsync(CustomerID); //find customer by CustomerID
            accountList = _context.Accounts.ToList();
            ViewBag.accountList = accountList;
            return View(customer);//return the target customer to the view
        }

     

        [HttpPost]
        public async Task<IActionResult> Transfer(string TransactionType, int FromAccount, int ToAccount, decimal amount, string Comment)
        {
            var customer = await _context.Customers.FindAsync(CustomerID);
          
            accountList = _context.Accounts.ToList();
            Manager.WithDrawOrDepositCheck(FromAccount,amount);
            if (!ModelState.IsValid)
            {
                ViewBag.Amount = amount;
                ViewBag.accountList = _context.Accounts.ToList();
                return View(customer);
            }
            switch (TransactionType) 
            {
                case "D":
                    if (await Manager.Deposit(FromAccount, amount))
                     return RedirectToAction("Index", "Customers");
                    break;
                case "W":
                    if (await Manager.Withdraw(FromAccount, amount))
                    {
                        return RedirectToAction("Index", "Customers");
                    }
                    else
                    {
                        ModelState.AddModelError("WithDrawFailed", "Withdraw failed, please check the amount and your account, and try again.");
                        ViewBag.Amount = amount;
                        ViewBag.accountList = _context.Accounts.ToList();
                        return View(customer);
                    }
                case "T":
                    if (await Manager.Transfer(FromAccount, ToAccount, amount, Comment))
                    {
                        return RedirectToAction("Index", "Customers");
                    }
                    else
                    {
                        ModelState.AddModelError("WithDrawFailed", "Transfer failed, please check the amount and your account, and try again.");
                        ViewBag.Amount = amount;
                        ViewBag.accountList = _context.Accounts.ToList();
                        return View(customer);
                    }
                default:
                    ModelState.AddModelError("WithDrawFailed", "Transfer failed, please try to refresh the page.");
                    ViewBag.Amount = amount;
                    ViewBag.accountList = _context.Accounts.ToList();
                    return View(customer);
            }


            return RedirectToAction("Index","Customers");
            
        }

    }
}

a2-s3673712-s3719368/a2-s3673712-s3719368/Areas/Default/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - a2_s3673712_s3719368</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>

    @* Navigation Bar *@
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="default" asp-controller="Logins" asp-action="Login">National Wealth Bank of Australasia</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav" style="float:right;">
                        <li class="nav nav-item" style="float:right;">
                            <a class="nav-link text-dark" asp-area="default" asp-controller="Logins" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="default" asp-controller="Customers" asp-action="Index">My-Statement</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="default" asp-controller="MyProfile" asp-action="Edit">My-Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="default" asp-controller="ATM" asp-action="Transfer">ATM</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="default" asp-controller="BillPays" asp-action="Index">Bills</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>



    @* Footer *@
    <footer class="border-top footer text-muted" style="background-color:white;">
        <div class="container">
            &copy; 2020 - a2_s3673712_s3719368 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>